version: "3.8"

services:
  app:
    image: dlckswn334/acc:1
    container_name: spring-app
    volumes:
      - ./logs:/app/logs  # Spring 애플리케이션의 로그 디렉토리와 공유
    ports:
      - "8080:8080"       # Spring 애플리케이션 포트
    restart: always
    depends_on:
      - fluent-bit

  fluent-bit:
    image: cr.fluentbit.io/fluent/fluent-bit:4.0
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc        # 설정 파일
      - ./logs:/fluent-bit/logs                 # 애플리케이션 로그 디렉토리
    ports:
      - "1111:1111"  # TCP JSON 로그 입력
      - "2020:2020"  # HTTP health (선택)
      - "2021:2021"  # Health check (선택)
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
    restart: always
